language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push omozokelvin/udagram-api-feed
  - docker push omozokelvin/udagram-api-user
  - docker push omozokelvin/udagram-frontend
  - docker push omozokelvin/reverseproxy