language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend omozokelvin/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push omozokelvin/udagram-frontend:v1