language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user omozokelvin/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push omozokelvin/udagram-api-user:v1